version: '3.8'

networks:
  monster:

services:
  db:
    image: postgres:12.1
    container_name: monster-postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - monster

  migrations:
    image: docker.pkg.github.com/bizarrelab/bizarre-monster/bizarre-monster-migrations:0.7.0
    container_name: monster-migrations
    environment:
      CONNECTION_STRING: 'Host=db; Username=postgres; Password=postgres'
      DELAY: 2000
      ASPNETCORE_ENVIRONMENT: 'Development'
    depends_on:
      - db
    networks:
      - monster

  api:
    # image: docker.pkg.github.com/bizarrelab/bizarre-monster/bizarre-monster:0.7.0
    image: bizarre-monster
    container_name: monster-api
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__Monster: 'Host=db; Username=postgres; Password=postgres'
      DELAY: 3000
    depends_on:
      - migrations
    networks:
      - monster

  front:
    build:
      context: .
      dockerfile: docker-dev.dockerfile
    container_name: front
    ports:
      - 8080:80
    depends_on:
      - api
    volumes:
      - ./public:/www
    networks:
      - monster
