version: '3.8'

networks:
  monster:

services:
  db:
    image: postgres:12.1
    container_name: monster-postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - monster

  migrations:
    image: docker.pkg.github.com/bizarrelab/bizarre-monster/bizarre-monster-migrations:0.7.0
    container_name: monster-migrations
    environment:
      CONNECTION_STRING: 'Host=db; Username=postgres; Password=postgres'
      DELAY: 3000
      ASPNETCORE_ENVIRONMENT: 'Development'
    depends_on:
      - db
    networks:
      - monster

  api:
    # image: docker.pkg.github.com/bizarrelab/bizarre-monster/bizarre-monster:0.7.0
    image: bizarre-monster
    container_name: monster-api
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__Monster: 'Host=db; Username=postgres; Password=postgres'
      DELAY: 6000
    depends_on:
      - migrations
    networks:
      - monster

  nginx:
    image: nginx:1.18.0
    container_name: monster-nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    volumes:
      - ./public:/www
      - ./nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
    networks:
      - monster
