version: '3.8'

networks:
  monster:

services:
  db:
    image: postgres:12.1
    container_name: mvp-postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - monster
    ports:
      - 5433:5432

  migrations:
    image: docker.pkg.github.com/bizarrelab/bizarre-monster/bizarre-monster-migrations:0.7.0
    container_name: mvp-migrations
    environment:
      CONNECTION_STRING: 'Host=db; Username=postgres; Password=postgres'
      DELAY: 3000
      ASPNETCORE_ENVIRONMENT: 'Development'
    depends_on:
      - db
    networks:
      - monster

  api:
    image: docker.pkg.github.com/bizarrelab/bizarre-monster/bizarre-monster:0.8.2
    container_name: mvp-api
    ports:
      - 5001:5001
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ASPNETCORE_URLS: 'https://+:5001'
      ASPNETCORE_HTTPS_PORT: 5001
      ASPNETCORE_Kestrel__Certificates__Default__Password: 'docker_password'
      ASPNETCORE_Kestrel__Certificates__Default__Path: '/https/dev-cert.pfx'
      ConnectionStrings__Monster: 'Host=db; Username=postgres; Password=postgres'
      DELAY: 6000
    depends_on:
      - migrations
    networks:
      - monster

  nginx:
    image: nginx:1.18.0
    container_name: mvp-nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    volumes:
      - ./public:/www
      - ./nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
    networks:
      - monster
